import { StyleSheet } from "react-native";
import { colors } from "@vyn/tokens";
import { fontFamily } from "../theme";

export const styles = StyleSheet.create({
  page: {
    padding: 16,
    backgroundColor: colors.surface.base,
    flexGrow: 1,
  },
  title: {
    fontSize: 28,
    fontWeight: "800",
    color: colors.brand[900],
    fontFamily,
  },
  step: {
    fontSize: 14,
    color: colors.ink[500],
    marginBottom: 16,
    fontFamily,
  },
  error: { color: colors.danger, marginBottom: 12, fontFamily },
  label: {
    fontSize: 15,
    fontWeight: "600",
    marginTop: 14,
    marginBottom: 6,
    color: colors.ink[900],
    fontFamily,
  },
  chips: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  chip: {
    borderWidth: 1.5,
    borderColor: colors.ink[300],
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 14,
  },
  chipSelected: {
    backgroundColor: colors.brand[500],
    borderColor: colors.brand[500],
  },
  chipText: { color: colors.ink[700], fontWeight: "600", fontFamily },
  chipTextSelected: { color: "#fff" },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 14,
  },
  stepper: { flexDirection: "row", alignItems: "center", gap: 12 },
  stepBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.brand[100],
    alignItems: "center",
    justifyContent: "center",
  },
  stepText: {
    fontSize: 20,
    color: colors.brand[900],
    fontWeight: "700",
    fontFamily,
  },
  stepValue: {
    fontSize: 18,
    fontWeight: "700",
    minWidth: 32,
    textAlign: "center",
    fontFamily,
  },
  input: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: colors.ink[100],
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    fontFamily,
    minHeight: 44,
  },
  primary: {
    backgroundColor: colors.brand[500],
    borderRadius: 8,
    padding: 14,
    alignItems: "center",
    marginTop: 24,
    minHeight: 44,
  },
  primaryText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 16,
    fontFamily,
  },
  secondary: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: colors.ink[100],
    borderRadius: 8,
    padding: 14,
    alignItems: "center",
    marginTop: 16,
    minHeight: 44,
  },
  secondaryText: {
    color: colors.brand[900],
    fontWeight: "700",
    fontSize: 16,
    fontFamily,
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: colors.ink[100],
  },
  cardDay: {
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1,
    textTransform: "uppercase",
    color: colors.primary.onFixedVariant,
    fontFamily,
  },
  cardTitle: { fontSize: 17, fontWeight: "700", marginTop: 2, fontFamily },
  cardSub: { fontSize: 14, color: colors.ink[500], marginTop: 2, fontFamily },
  rationale: {
    fontSize: 13,
    color: colors.ink[500],
    marginTop: 12,
    fontFamily,
  },
  homeTop: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    marginBottom: 8,
  },
  scoreCircle: {
    width: 84,
    height: 84,
    borderRadius: 42,
    borderWidth: 6,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
  },
  scoreNum: { fontSize: 26, fontWeight: "800", color: colors.ink[900] },
  streakFlame: { fontSize: 18, fontWeight: "700" },
  cardActive: { borderColor: colors.brand[500], borderWidth: 2 },
  btnRow: { flexDirection: "row", gap: 10, marginTop: 16 },
  pendingBanner: {
    backgroundColor: colors.accent[100],
    color: colors.accent[600],
    fontWeight: "700",
    padding: 10,
    borderRadius: 10,
    marginBottom: 10,
    overflow: "hidden",
  },
  doneMsg: { fontSize: 14, fontWeight: "700", marginTop: 12 },
  bookmark: {
    fontSize: 15,
    fontWeight: "700",
    color: colors.brand[700],
    marginTop: 8,
  },
  barRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 6,
  },
  barLabel: { fontSize: 12, color: colors.ink[500], width: 44 },
  barTrack: {
    flex: 1,
    height: 8,
    borderRadius: 999,
    backgroundColor: colors.surface.container,
    overflow: "hidden",
  },
  barFill: { height: 8, backgroundColor: colors.brand[500] },
  barValue: {
    fontSize: 13,
    fontWeight: "700",
    width: 28,
    textAlign: "right",
    fontFamily,
  },
  goalRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: colors.ink[100],
  },
  checkbox: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 2,
    borderColor: colors.brand[500],
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxDone: { backgroundColor: colors.brand[500] },
  checkboxText: { color: "#fff", fontWeight: "700" },
  goalTitle: { flex: 1, fontSize: 15, fontWeight: "600" },
  goalDone: { textDecorationLine: "line-through", color: colors.ink[500] },
  goalDelete: { fontSize: 16, color: colors.danger, padding: 4 },
  shell: { flex: 1, backgroundColor: colors.surface.base },
  scroller: { flex: 1 },
  centerWrap: { alignItems: "center", paddingVertical: 60 },
  splashWrap: {
    alignItems: "center",
    paddingVertical: 60,
    backgroundColor: colors.brand[900],
    borderRadius: 24,
    paddingHorizontal: 24,
  },
  splashTitle: {
    fontSize: 32,
    fontWeight: "800",
    color: "#fff",
    marginTop: 16,
    fontFamily,
  },
  splashTag: {
    fontSize: 15,
    color: colors.brand[100],
    marginTop: 4,
    fontFamily,
  },
  splashLoader: {
    height: 4,
    width: 160,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.2)",
    marginTop: 24,
    overflow: "hidden",
  },
  splashLoaderFill: {
    height: "100%",
    width: "60%",
    backgroundColor: colors.brand[100],
    borderRadius: 999,
  },
  splashLogo: { fontSize: 64, fontWeight: "800", color: colors.brand[700] },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
    backgroundColor: "rgba(249, 249, 255, 0.9)",
    paddingVertical: 8,
  },
  headerBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.surface.container,
    alignItems: "center",
    justifyContent: "center",
  },
  headerIcon: { fontSize: 18 },
  headerTitle: { fontSize: 18, fontWeight: "800", fontFamily },
  tabBar: {
    flexDirection: "row",
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: colors.ink[100],
    paddingTop: 6,
    paddingBottom: 16,
    minHeight: 64,
  },
  tab: { flex: 1, alignItems: "center", minHeight: 44 },
  tabIcon: { fontSize: 20 },
  tabLabel: { fontSize: 11, color: colors.ink[500], fontFamily },
  tabActive: { color: colors.brand[500], fontWeight: "700" },
  drawerOverlay: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
  },
  drawerScrim: { flex: 1, backgroundColor: "rgba(0,0,0,0.35)" },
  drawer: { width: 250, backgroundColor: "#fff", padding: 20 },
  drawerTitle: {
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 12,
    fontFamily,
  },
  drawerItem: { paddingVertical: 12, minHeight: 44 },
  drawerText: { fontSize: 16, fontFamily },
  moodRow: { flexDirection: "row", gap: 8, marginBottom: 8 },
  mood: {
    flex: 1,
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.ink[100],
    borderRadius: 8,
    paddingVertical: 8,
    minHeight: 44,
  },
  moodSelected: {
    borderColor: colors.brand[500],
    backgroundColor: colors.brand[50],
  },
  moodEmoji: { fontSize: 24 },
  moodLabel: { fontSize: 11, color: colors.ink[700], fontFamily },
  checklistRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 8,
  },
  checkDot: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: colors.brand[500],
    alignItems: "center",
    justifyContent: "center",
  },
  checkDone: { backgroundColor: colors.brand[500] },
  checkText: { color: "#fff", fontWeight: "700" },
  checklistText: { fontSize: 15, flex: 1 },
});

export type AppStyles = typeof styles;
